trigger:
- master

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: yarn install
  displayName: 'Yarn install'

- script: yarn run build
  displayName: 'Build'

- script: yarn pack
  displayName: 'Pack'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '*.tgz'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
